FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_HORIZON_API_BASE_URL=http://localhost:8000
ARG VITE_HORIZON_CONFIG_URL
ARG VITE_HORIZON_EXPORT_ID=demo-export
ARG VITE_HORIZON_ENABLE_ADMIN_PANEL=false
ARG VITE_HORIZON_ADMIN_DEFAULT_WORKSPACE_ID=

ENV VITE_HORIZON_API_BASE_URL=${VITE_HORIZON_API_BASE_URL}
ENV VITE_HORIZON_CONFIG_URL=${VITE_HORIZON_CONFIG_URL}
ENV VITE_HORIZON_EXPORT_ID=${VITE_HORIZON_EXPORT_ID}
ENV VITE_HORIZON_ENABLE_ADMIN_PANEL=${VITE_HORIZON_ENABLE_ADMIN_PANEL}
ENV VITE_HORIZON_ADMIN_DEFAULT_WORKSPACE_ID=${VITE_HORIZON_ADMIN_DEFAULT_WORKSPACE_ID}

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
